# Generated by Django 5.1.15 on 2026-06-11 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('index', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('contest_id', 'index')},
            },
        ),
        migrations.CreateModel(
            name='CodeforcesContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('contest_name', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('rating_update_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rating_update_time'],
                'unique_together': {('user', 'contest_id')},
            },
        ),
        migrations.CreateModel(
            name='TopicStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('solved_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_count'],
                'unique_together': {('user', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserSolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvers', to='codeforces.codeforcesproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
